# Generated by Django 3.1 on 2020-08-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eu_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='documento_identidad_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_documentoidentidadtipo', to='comun.documentoidentidadtipo'),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='empresa_representante_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_empresarepresentantetipo', to='comun.empresarepresentantetipo'),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_nacionalidad', to='comun.pais'),
        ),
        migrations.AddField(
            model_name='empresaredsocial',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ers_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresaredsocial',
            name='red_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ers_redsocial', to='comun.redsocial'),
        ),
        migrations.AddField(
            model_name='empresaparticipacionaccionaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epa_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresaparticipacionaccionaria',
            name='empresa_representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epa_empresarepresentante', to='comun.empresarepresentante'),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='el_distrito', to='comun.distrito'),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='el_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='empresa_locacion_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='el_empresalocaciontipo', to='comun.empresalocaciontipo'),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='el_pais', to='comun.pais'),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='el_provincia', to='comun.provincia'),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='el_region', to='comun.region'),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eib_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='financiera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eib_financiera', to='comun.financiera'),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='moneda_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eib_monedacuenta', to='comun.moneda'),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eib_tipocuenta', to='comun.tipocuentabancaria'),
        ),
        migrations.AddField(
            model_name='empresaexperienciadocumentacion',
            name='empresa_experiencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eed_empresaexperiencia', to='comun.empresaexperiencia'),
        ),
        migrations.AddField(
            model_name='empresaexperiencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ee_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresaexperiencia',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ee_monedacuenta', to='comun.moneda'),
        ),
        migrations.AddField(
            model_name='empresacertificacion',
            name='certificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ec_certificacion', to='comun.certificacion'),
        ),
        migrations.AddField(
            model_name='empresacertificacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ec_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresaarchivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ea_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresaarchivo',
            name='empresa_archivo_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ea_empresaarchivotipo', to='comun.empresaarchivotipo'),
        ),
        migrations.AddField(
            model_name='empresaactividadeconomica',
            name='actividad_economica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eac_actividadeconomica', to='comun.actividadeconomica'),
        ),
        migrations.AddField(
            model_name='empresaactividadeconomica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eac_empresa', to='comun.empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='e_tipopersona', to='comun.tipopersona'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_sociedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='e_tiposociedad', to='comun.tiposociedad'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distrito_provincia', to='comun.provincia'),
        ),
    ]
