# Generated by Django 3.1 on 2020-08-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0003_auto_20200809_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresarepresentantetipo',
            old_name='nombre_completo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='empresarepresentantetipo',
            name='nombre_corto',
        ),
    ]
