# Generated by Django 3.1 on 2020-08-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0005_auto_20200823_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='nombre_corto',
            field=models.CharField(default='', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
