# Generated by Django 3.1 on 2020-08-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0006_moneda_nombre_corto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaRubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquetas', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erubro_empresa', to='comun.empresa')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erubro_rubro', to='comun.rubro')),
            ],
        ),
    ]
