# Generated by Django 3.1 on 2020-08-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0007_empresarubro_rubro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresatags',
            name='tags',
        ),
    ]
