# Generated by Django 3.1 on 2020-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0008_remove_empresatags_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresatags',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
