# Generated by Django 3.1 on 2020-09-01 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0009_empresatags_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaLocacionFotoTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='empresarubro',
            name='etiquetas',
            field=models.JSONField(default=dict),
        ),
    ]
