# Generated by Django 3.1 on 2020-09-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0011_empresalocacionfototicket_empresa_locacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresarepresentante',
            name='vencimiento_documento_identidad',
        ),
    ]
