# Generated by Django 3.1 on 2020-09-13 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comun', '0014_auto_20200903_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadeconomica',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividadeconomica_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividadeconomica_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividadeconomica_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificacion_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificacion_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificacion_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distrito',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distrito_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='distrito',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='distrito',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distrito_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distrito',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distrito_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaciontipo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentaciontipo_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='documentaciontipo',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documentaciontipo',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='documentaciontipo',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentaciontipo_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaciontipo',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentaciontipo_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoidentidadtipo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentoidentidadtipo_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='documentoidentidadtipo',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoidentidadtipo',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoidentidadtipo',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentoidentidadtipo_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoidentidadtipo',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentoidentidadtipo_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaactividadeconomica',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaactividadeconomica_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresaactividadeconomica',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaactividadeconomica',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaactividadeconomica',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaactividadeconomica_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaactividadeconomica',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaactividadeconomica_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaarchivo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaarchivo_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresaarchivo',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaarchivo',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaarchivo',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaarchivo_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaarchivo',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaarchivo_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaarchivotipo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaarchivotipo_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresaarchivotipo',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaarchivotipo',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaarchivotipo',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaarchivotipo_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaarchivotipo',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaarchivotipo_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresacertificacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresacertificacion_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresacertificacion',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresacertificacion',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresacertificacion',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresacertificacion_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresacertificacion',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresacertificacion_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresadocumentacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresadocumentacion_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresadocumentacion',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresadocumentacion',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresadocumentacion',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresadocumentacion_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresadocumentacion',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresadocumentacion_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaexperiencia',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaexperiencia_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresaexperiencia',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaexperiencia',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaexperiencia',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaexperiencia_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaexperiencia',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaexperiencia_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaexperienciadocumentacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaexperienciadocumentacion_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresaexperienciadocumentacion',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaexperienciadocumentacion',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaexperienciadocumentacion',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaexperienciadocumentacion_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaexperienciadocumentacion',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaexperienciadocumentacion_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresainformacionbancaria_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresainformacionbancaria_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresainformacionbancaria',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresainformacionbancaria_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocacion_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocacion_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresalocacion',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocacion_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresalocacionfototicket',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocacionfototicket_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresalocacionfototicket',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresalocacionfototicket',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresalocacionfototicket',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocacionfototicket_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresalocacionfototicket',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocacionfototicket_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresalocaciontipo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocaciontipo_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresalocaciontipo',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresalocaciontipo',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresalocaciontipo',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocaciontipo_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresalocaciontipo',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocaciontipo_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaparticipacionaccionaria',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaparticipacionaccionaria_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresaparticipacionaccionaria',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaparticipacionaccionaria',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaparticipacionaccionaria',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaparticipacionaccionaria_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaparticipacionaccionaria',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaparticipacionaccionaria_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaredsocial',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaredsocial_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresaredsocial',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaredsocial',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaredsocial',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaredsocial_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaredsocial',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaredsocial_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarepresentante_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarepresentante_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresarepresentante',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarepresentante_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresarepresentantetipo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarepresentantetipo_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresarepresentantetipo',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresarepresentantetipo',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresarepresentantetipo',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarepresentantetipo_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresarepresentantetipo',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarepresentantetipo_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresarubro',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarubro_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresarubro',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresarubro',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresarubro',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarubro_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresarubro',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarubro_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresatags',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresatags_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresatags',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresatags',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresatags',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresatags_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresatags',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresatags_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresausuario_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresausuario_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresausuario_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financiera',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiera_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='financiera',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='financiera',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiera_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financiera',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiera_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informaciontributaria',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informaciontributaria_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='informaciontributaria',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='informaciontributaria',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='informaciontributaria',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informaciontributaria_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informaciontributaria',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informaciontributaria_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moneda',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moneda_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moneda',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='moneda',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moneda_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moneda',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moneda_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='pais',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfilusuario_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfilusuario_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfilusuario_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincia',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provincia_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provincia_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincia',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provincia_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redsocial_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redsocial_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redsocial_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regimenrecaudacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regimenrecaudacion_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='regimenrecaudacion',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='regimenrecaudacion',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='regimenrecaudacion',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regimenrecaudacion_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regimenrecaudacion',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regimenrecaudacion_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='region',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubro',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubro_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rubro',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rubro',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubro_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubro',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubro_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='tags',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipocuentabancaria_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipocuentabancaria_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipocuentabancaria_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipopersona',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipopersona_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='tipopersona',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipopersona',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tipopersona',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipopersona_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipopersona',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipopersona_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiposociedad',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposociedad_estado', to='comun.estado'),
        ),
        migrations.AddField(
            model_name='tiposociedad',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tiposociedad',
            name='fecha_modif',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tiposociedad',
            name='usuario_crea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposociedad_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiposociedad',
            name='usuario_modif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposociedad_modificado', to=settings.AUTH_USER_MODEL),
        ),
    ]
