# Generated by Django 3.1 on 2020-09-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0015_auto_20200913_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadeconomica',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividadeconomica_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificacion_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distrito_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='documentaciontipo',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentaciontipo_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='documentoidentidadtipo',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentoidentidadtipo_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresaactividadeconomica',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaactividadeconomica_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresaarchivo',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaarchivo_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresaarchivotipo',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaarchivotipo_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresacertificacion',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresacertificacion_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresadocumentacion',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresadocumentacion_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresaexperiencia',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaexperiencia_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresaexperienciadocumentacion',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaexperienciadocumentacion_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresainformacionbancaria',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresainformacionbancaria_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresalocacion',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocacion_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresalocacionfototicket',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocacionfototicket_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresalocaciontipo',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresalocaciontipo_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresaparticipacionaccionaria',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaparticipacionaccionaria_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresaredsocial',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresaredsocial_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresarepresentante',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarepresentante_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresarepresentantetipo',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarepresentantetipo_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresarubro',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresarubro_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresatags',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresatags_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='empresausuario',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresausuario_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='financiera',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiera_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='informaciontributaria',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informaciontributaria_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moneda_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfilusuario_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provincia_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='redsocial',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redsocial_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='regimenrecaudacion',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regimenrecaudacion_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='region',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubro_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='tipocuentabancaria',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipocuentabancaria_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipopersona_estado', to='comun.estado'),
        ),
        migrations.AlterField(
            model_name='tiposociedad',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposociedad_estado', to='comun.estado'),
        ),
    ]
